### PR TITLE
Add README.md in resources folder

### PR DESCRIPTION
**Pull request by haykam821**

### CODE REVIEW

**Review by thehappydinoa — COMMENTED** [review]
I am not sure if this is needed.

**Comment by haykam821** [comment]
@thehappydinoa It’s so people can stop being confused when they don’t find the IPA in this folder because we switched to GitHub releases.

**Comment by thehappydinoa** [comment]
Ah check out #340 we clear up that information in the master README

**Comment by haykam821** [comment]
@thehappydinoa That doesn’t help when an old tutorial links directly to the folder. Also, most users can’t read.

**Comment by thehappydinoa** [comment]
You make a good point

**Comment by T4shf33n** [comment]
@thehappydinoa @haykam821  May I combine this with #340 ?

**Comment by T4shf33n** [comment]
I have combined this to #340  to make easier to merge and also fixed the links and renamed the readme . Thanks @haykam821

**Comment by haykam821** [comment]
@T4shf33n You just made it worse. Your grammar is incorrect and it is no longer a proper README.

**Comment by Chasewhip8** [comment]
I fixed the grammar with a pull request a while back. Maybe point out the grammar instead of dissing on it?

**Comment by haykam821** [comment]
@Chasewhip8 Unfortunately I can't find that pull request.

**Comment by T4shf33n** [comment]
@Chasewhip8 I merged your request

**Pull request closed without merging**
