### PR TITLE
New UI Implemented

### PR DESCRIPTION
**Pull request by kjwamlex**
pls users stop torturing me /s

### CODE REVIEW

**Comment by Samgisaninja** [comment]
looks amazing <3

**Comment by Samgisaninja** [comment]
pushed 5b9547684e4b0814866574db03daa540e36d85e8... I think you forgot to remove an Xcode reference to a file that you moved... anyways, it compiles now

**Comment by jailbreaklover** [comment]
Thanks boyss

**Comment by himynameisubik** [comment]
go fast @kjwamlex ;)

**Pull request merged**
