### PR TITLE
Add 12.4 to README.md

### PR DESCRIPTION
**Pull request by ntindle**

### CODE REVIEW

**Review by degoo511 — APPROVED** [review]

**Comment by Alexandra1001** [comment]
It worked for me at first now it saying unsupported

**Comment by Quintanasp18** [comment]
Não estou conseguindo fazer nada depois do tutorial, alguém me ajudar?🙏🏻🙏🏻

**Comment by ganimine** [comment]
Hi  Sir.   Please respond if you see these line to ganimine@gmail.com . I want to know the it can remove the existed iCloud account perminantly on having iOS 12.4 of any device?

**Comment by ntindle** [comment]
@Alexandra1001 @Quintanasp18 @ganimine Open an issue. This is not related to this PR

**Review by Slingblade7 — APPROVED** [review]

**Pull request closed without merging**
