### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codivilian**
remove enable purchases on iOS 11

### CODE REVIEW

**Comment by T4shf33n** [comment]
Cydia store purchase is a thing that should be enabled. Isn’t it? As users don’t need to rely on the Dev to process purchases

**Comment by codivilian** [comment]
They have to be on third party repos because the actual Cydia store has
been disabled

**Comment by T4shf33n** [comment]
Also you can suggest and discuss the changes on Pull Request #340 . Which is currently under development by the participants

**Comment by T4shf33n** [comment]
And that’s the reason it’s on the pending list

**Comment by Samgisaninja** [comment]
Please combine this with #340

**Pull request closed without merging**
