### PR TITLE
Update version number

### PR DESCRIPTION
**Pull request by pugthelouie**
As simple as the title.

### CODE REVIEW

**Comment by clubby789** [comment]
I'm pretty sure this change has been made on whatever branch own builds from, I've got b31 and it says 12.1.2

**Comment by j0k3r** [comment]
It's already done in the develop branch, see https://github.com/pwn20wndstuff/Undecimus/commit/349dac7da0d60ca1d6054c33c581ac31aa3f108a

**Comment by clubby789** [comment]
Pity it hasn't been updated in master yet

**Comment by king4q** [comment]
@Cryptiiic please close this it’s not relevant.

**Comment by Samgisaninja** [comment]
we build from develop... and the version number is automatically generated...

**Pull request closed without merging**
