### PR TITLE
Add support for running expired or revoked apps on iOS 12.0-12.4

### PR DESCRIPTION
**Pull request by profiles**

### CODE REVIEW

**Comment by IMS212** [comment]
Probably not this easy. Jake said that something broke in iOS 12 that doesn’t allow this method to be used anymore, I tried dming him a month ago and he didn’t respond.

Also this is not the iOS 12.4 unc0ver branch, this is either the 12.1.2 or 12.2 branch (the 12.4 branch is private)

**Comment by profiles** [comment]
Oops...

But I have tried this by using shell command... and it's effective...😂

**Comment by IMS212** [comment]
Oh nice, btw jake james’ nomorerevocations on his repo should do the same thing

**Comment by IMS212** [comment]
But we should probably close this pr until the 12.4 branch goes public (hopefully on a12 release)

**Comment by IMS212** [comment]
ok, found the reason it was disabled on 12+; it caused stability issues
Also, this wouldn’t work in non-jail broken mode theoretically because iOS 12 ignores hosts file

**Comment by profiles** [comment]
Ok~,   got it,  Thank you~

**Comment by linux3ronga** [comment]
Use antirevoke by 180

**Pull request closed without merging**
